export type HttpCodes =
  | 'OK'
  | 'Created'
  | 'Accepted'
  | 'NoContent'
  | 'BadRequest'
  | 'Unauthorized'
  | 'Forbidden'
  | 'NotFound'
  | 'Conflict'
  | 'ImATeapot'
  | 'UnprocessableEntity'
  | 'TooManyRequests'
  | 'InternalServerError'
  | 'BadGateway'
  | 'ServiceUnavailable'
